Repository primodiumxyz/indexer, pull requests merged in 2024-04, with the labels that each got.

#7 Update MUD to v2.0.1
  packages/sync-stack/examples/_constants.ts
  packages/sync-stack/examples/read/decoded-indexer/queryTable.ts
  packages/sync-stack/examples/read/decoded-indexer/queryTableWithConditions.ts
  packages/sync-stack/examples/read/indexer/queryStoreTableRecords.ts
  packages/sync-stack/examples/read/rpc/queryLogsBlockRange.ts
  packages/sync-stack/examples/read/rpc/subToRpcWithFilter.ts
  packages/sync-stack/examples/sync/syncToConsole.ts
  packages/sync-stack/examples/sync/syncWithRecs.ts
  packages/sync-stack/examples/sync/syncWithRecsFromIndexer.ts
  packages/sync-stack/examples/write/syncWithRecs.ts
  packages/sync-stack/package.json
  packages/sync-stack/src/sync/factories/customSync.ts
  packages/sync-stack/src/types.ts
  packages/sync-stack/src/utils/debug.ts
  packages/sync-stack/src/utils/recs.ts
  packages/sync-stack/src/write/writers/recsWriter.ts
  pnpm-lock.yaml
Labels: kind/feature, status/testing

#8 Revert Debug imports for build
  packages/sync-stack/src/utils/debug.ts
Labels: kind/bug, status/testing

#9 Update MUD to v2.0.6
  packages/sync-stack/package.json
  pnpm-lock.yaml
Labels: kind/infra, status/in-progress

#10 Update viem to 2.9.20
  packages/sync-stack/package.json
  pnpm-lock.yaml
Labels: kind/infra
